#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
xsetroot -cursor_name left_ptr &

feh --bg-scale "$HOME/Pictures/picture.jpg" &

"$HOME/.config/polybar/launch.sh" &

dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#414868"
bspc config active_border_color "#7dcfff"
bspc config focused_border_color "#7aa2f7"
bspc config presel_feedback_color "#bb9af7"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pkill -f "$HOME/.local/bin/bspwm-urgent-watch" 2>/dev/null
"$HOME/.local/bin/bspwm-urgent-watch" &
